line-length = 120
target-version = "py312"

exclude = ["src/forge_cli/response/_types"]

[lint]
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "Q",  # flake8-quotes
    "B",  # flake8-bugbear
    "C4", # flake8-comprehensions
    "UP", # pyupgrade
    "N",  # pep8-naming
    # "SIM", # flake8-simplify
    # "RUF", # ruff-specific rules
    # "PL",  # pylint
    # "C90", # mccabe complexity
]

ignore = [
    "RUF001",
    "E501",   # line too long (handled by formatter)
    "B003",   # assign to variable in except block
    "B007",   # unused loop control variable
    "B009",   # get() with default mutable
    "B010",   # setattr with constant
    "B904",   # raise without from
    "B018",   # useless expression
    "N806",   # variable in function should be lowercase
    # "PLR0913", # too many arguments
    "PLR2004", # magic value comparison
    "SIM108",  # use ternary operator
]

[lint.flake8-quotes]
docstring-quotes = "double"
inline-quotes = "double"

[lint.isort]
known-first-party = ["jtools"]
split-on-trailing-comma = true

# [lint.mccabe]
# max-complexity = 10

[lint.pylint]
max-args = 10


[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
