"""Type guards and utilities for Response types to enable proper type narrowing.

This module provides a unified interface to all type guards by importing them from sub-modules.
"""

# Import all type guards from sub-modules
from .annotations import (
    is_file_citation,
    is_file_path,
    is_url_citation,
)
from .content import (
    get_content_refusal,
    get_content_text,
    is_output_refusal,
    is_output_text,
)
from .events import (
    get_event_type,
    is_audio_delta_event,
    is_audio_done_event,
    is_audio_transcript_delta_event,
    is_audio_transcript_done_event,
    is_code_interpreter_call_code_delta_event,
    is_code_interpreter_call_code_done_event,
    is_code_interpreter_call_completed_event,
    is_code_interpreter_call_in_progress_event,
    is_code_interpreter_call_interpreting_event,
    is_content_part_added_event,
    is_content_part_done_event,
    is_error_event,
    is_file_search_call_completed_event,
    is_file_search_call_in_progress_event,
    is_file_search_call_searching_event,
    is_function_call_arguments_delta_event,
    is_function_call_arguments_done_event,
    is_in_progress_event,
    is_incomplete_event,
    is_output_item_added_event,
    is_output_item_done_event,
    is_reasoning_summary_part_added_event,
    is_reasoning_summary_part_done_event,
    is_reasoning_summary_text_delta_event,
    is_reasoning_summary_text_done_event,
    is_refusal_delta_event,
    is_refusal_done_event,
    is_response_completed_event,
    is_response_created_event,
    is_response_failed_event,
    is_text_annotation_delta_event,
    is_text_delta_event,
    is_text_done_event,
    is_web_search_call_completed_event,
    is_web_search_call_in_progress_event,
    is_web_search_call_searching_event,
)
from .input_content import (
    is_input_file,
    is_input_image,
    is_input_text,
)
from .output_items import (
    is_code_interpreter_call,
    is_computer_tool_call,
    is_document_finder_call,
    is_file_reader_call,
    is_file_search_call,
    is_function_call,
    is_message_item,
    is_reasoning_item,
    is_web_search_call,
)
from .status import (
    is_response_completed_status,
    is_response_error,
    is_response_failed_status,
    is_response_in_progress_status,
    is_response_incomplete_status,
)
from .tools import (
    is_computer_tool,
    is_document_finder_tool,
    is_file_reader_tool,
    is_file_search_tool,
    is_function_tool,
    is_web_search_tool,
)
from .utilities import (
    get_error_code,
    get_error_message,
    get_tool_arguments,
    get_tool_call_id,
    get_tool_call_status,
    get_tool_call_type,
    get_tool_content,
    get_tool_function_name,
    get_tool_output,
    get_tool_queries,
    get_tool_results,
    is_any_tool_call,
    is_assistant_message_dict,
    is_code_interpreter_files,
    is_code_interpreter_logs,
    is_computer_action_click,
    is_computer_action_double_click,
    is_computer_action_drag,
    is_computer_action_keypress,
    is_computer_action_move,
    is_computer_action_screenshot,
    is_computer_action_scroll,
    is_computer_action_type,
    is_computer_action_wait,
    is_computer_tool_output,
    is_dict_with_type,
    is_execution_tool_call,
    is_search_related_tool_call,
    is_tool_call_completed,
    is_tool_call_failed,
    is_tool_call_in_progress,
    is_tool_call_interpreting,
    is_tool_call_searching,
    safe_get_attr,
)

# Re-export all functions for backward compatibility
__all__ = [
    # Annotations
    "is_file_citation",
    "is_file_path",
    "is_url_citation",
    # Content
    "get_content_refusal",
    "get_content_text",
    "is_output_refusal",
    "is_output_text",
    # Events
    "get_event_type",
    "is_audio_delta_event",
    "is_audio_done_event",
    "is_audio_transcript_delta_event",
    "is_audio_transcript_done_event",
    "is_code_interpreter_call_code_delta_event",
    "is_code_interpreter_call_code_done_event",
    "is_code_interpreter_call_completed_event",
    "is_code_interpreter_call_in_progress_event",
    "is_code_interpreter_call_interpreting_event",
    "is_content_part_added_event",
    "is_content_part_done_event",
    "is_error_event",
    "is_file_search_call_completed_event",
    "is_file_search_call_in_progress_event",
    "is_file_search_call_searching_event",
    "is_function_call_arguments_delta_event",
    "is_function_call_arguments_done_event",
    "is_in_progress_event",
    "is_incomplete_event",
    "is_output_item_added_event",
    "is_output_item_done_event",
    "is_reasoning_summary_part_added_event",
    "is_reasoning_summary_part_done_event",
    "is_reasoning_summary_text_delta_event",
    "is_reasoning_summary_text_done_event",
    "is_refusal_delta_event",
    "is_refusal_done_event",
    "is_response_completed_event",
    "is_response_created_event",
    "is_response_failed_event",
    "is_text_annotation_delta_event",
    "is_text_delta_event",
    "is_text_done_event",
    "is_web_search_call_completed_event",
    "is_web_search_call_in_progress_event",
    "is_web_search_call_searching_event",
    # Input content
    "is_input_file",
    "is_input_image",
    "is_input_text",
    # Output items
    "is_code_interpreter_call",
    "is_computer_tool_call",
    "is_document_finder_call",
    "is_file_reader_call",
    "is_file_search_call",
    "is_function_call",
    "is_message_item",
    "is_reasoning_item",
    "is_web_search_call",
    # Status
    "is_response_completed_status",
    "is_response_error",
    "is_response_failed_status",
    "is_response_in_progress_status",
    "is_response_incomplete_status",
    # Tools
    "is_computer_tool",
    "is_document_finder_tool",
    "is_file_reader_tool",
    "is_file_search_tool",
    "is_function_tool",
    "is_web_search_tool",
    # Utilities
    "get_error_code",
    "get_error_message",
    "get_tool_arguments",
    "get_tool_call_id",
    "get_tool_call_status",
    "get_tool_call_type",
    "get_tool_content",
    "get_tool_function_name",
    "get_tool_output",
    "get_tool_queries",
    "get_tool_results",
    "is_any_tool_call",
    "is_assistant_message_dict",
    "is_code_interpreter_files",
    "is_code_interpreter_logs",
    "is_computer_action_click",
    "is_computer_action_double_click",
    "is_computer_action_drag",
    "is_computer_action_keypress",
    "is_computer_action_move",
    "is_computer_action_screenshot",
    "is_computer_action_scroll",
    "is_computer_action_type",
    "is_computer_action_wait",
    "is_computer_tool_output",
    "is_dict_with_type",
    "is_execution_tool_call",
    "is_search_related_tool_call",
    "is_tool_call_completed",
    "is_tool_call_failed",
    "is_tool_call_in_progress",
    "is_tool_call_interpreting",
    "is_tool_call_searching",
    "safe_get_attr",
]
